name: ci-test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Password123
          POSTGRES_DB: crud_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Install dbmate for golang migrations
        run: |
          curl -O https://github.com/amacneil/dbmate/releases/latest/download/dbmate-linux-amd64
          sudo mv dbmate-linux-amd64 /usr/bin

      - name: MakeMigrations
        run: make migrations

      - name: Test
        run: make test
